### ISSUE TITLE
Can't run skeleton app, didn't get a depth buffer

### ISSUE THREAD

**Issue by IoriBranford** [excessive/love3d#6]
1. Create project folder with love3d, cpml, bin/SDL2.dll ([latest win32-x64](http://libsdl.org/download-2.0.php)), and minimal main.lua: `require("love3d").import(true)`
1. Run LOVE 0.10.2 x64 on project folder

This bugged out on my machine (Win7 64, Intel Graphics HD 3000 with latest drivers). Even before using any love3d functions.

> Error: love3d/init.lua:102: We didn't get a depth buffer, bad things will happen.
> stack traceback:
>	[C]: in function 'assert'
>	love3d/init.lua:102: in function 'import'

Other SDL2 OpenGL applications run OK (e.g. [ioquake3](https://github.com/ioquake/ioq3), even in the new OpenGL 2 rendering mode). So I don't think the problem is in SDL2 or my hardware.

**Comment by shakesoda** [comment]
this should be fixed, the assert was removed. if you don't get depth make a canvas with depth and it should be OK.
